name: masir
description: Persian-first free Waze-like navigation app built with Flutter, MapLibre and OpenStreetMap.
publish_to: 'none'
version: 0.8.0+9

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  maplibre_gl: ^0.27.1
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  dio: ^5.11.1
  equatable: ^3.0.0
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
