name: masir
description: Persian-first open navigation app built with Flutter and OpenStreetMap.
publish_to: 'none'
version: 0.8.1+10

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.3.2
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.3
  latlong2: ^0.9.1
  dio: ^5.11.1
  equatable: ^3.0.0
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  flutter_tts: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
